package pe.gob.sunat.recurso2.administracion.siga.registro.model.dao;

import java.util.List;
import pe.gob.sunat.recurso2.administracion.siga.registro.model.bean.Dds;

public interface DdsDAO {

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VWDDS
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    List<Dds> selectByExample(Dds example);
}