package pe.gob.sunat.recurso2.administracion.siga.registro.model.dao;

import java.util.List;
import pe.gob.sunat.recurso2.administracion.siga.registro.model.bean.T733Pernat;

public interface T733PernatDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VWT733PERNAT
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    List<T733Pernat> selectByExample(T733Pernat example);
}