package pe.gob.sunat.recurso2.administracion.siga.firma.model.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.sunat.recurso2.administracion.siga.firma.model.bean.T7073FirmaElectron;
import pe.gob.sunat.recurso2.administracion.siga.firma.model.dao.T7073FirmaElectronDAO;

public class SqlMapT7073FirmaElectronDAOImpl extends SqlMapClientDaoSupport implements T7073FirmaElectronDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7073FIRMAELECTRON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public SqlMapT7073FirmaElectronDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7073FIRMAELECTRON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int deleteByPrimaryKey(String codFirma) {
        T7073FirmaElectron key = new T7073FirmaElectron();
        key.setCodFirma(codFirma);
        int rows = getSqlMapClientTemplate().delete("t7073firmaelectron.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7073FIRMAELECTRON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void insert(T7073FirmaElectron record) {
        getSqlMapClientTemplate().insert("t7073firmaelectron.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7073FIRMAELECTRON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void insertSelective(T7073FirmaElectron record) {
        getSqlMapClientTemplate().insert("t7073firmaelectron.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7073FIRMAELECTRON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public T7073FirmaElectron selectByPrimaryKey(String codFirma) {
        T7073FirmaElectron key = new T7073FirmaElectron();
        key.setCodFirma(codFirma);
        T7073FirmaElectron record = (T7073FirmaElectron) getSqlMapClientTemplate().queryForObject("t7073firmaelectron.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7073FIRMAELECTRON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int updateByPrimaryKeySelective(T7073FirmaElectron record) {
        int rows = getSqlMapClientTemplate().update("t7073firmaelectron.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7073FIRMAELECTRON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int updateByPrimaryKey(T7073FirmaElectron record) {
        int rows = getSqlMapClientTemplate().update("t7073firmaelectron.updateByPrimaryKey", record);
        return rows;
    }
    
    public List<T7073FirmaElectron> listByParameter(T7073FirmaElectron param) {
        List<T7073FirmaElectron> list = (List<T7073FirmaElectron>) getSqlMapClientTemplate().queryForList("t7073firmaelectron.listByParameter", param);
        return list;
    }
}