package pe.gob.sunat.recurso2.administracion.siga.firma.model.dao.ibatis;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.sunat.recurso2.administracion.siga.firma.model.bean.T7074DocumentoFirm;
import pe.gob.sunat.recurso2.administracion.siga.firma.model.bean.T7075TerminoCond;
import pe.gob.sunat.recurso2.administracion.siga.firma.model.dao.T7075TerminoCondDAO;

public class SqlMapT7075TerminoCondDAOImpl extends SqlMapClientDaoSupport implements T7075TerminoCondDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7075TERMINOCOND
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public SqlMapT7075TerminoCondDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7075TERMINOCOND
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int deleteByPrimaryKey(BigDecimal codTerycon) {
        T7075TerminoCond key = new T7075TerminoCond();
        key.setCodTerycon(codTerycon);
        int rows = getSqlMapClientTemplate().delete("t7075terminocond.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7075TERMINOCOND
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void insert(T7075TerminoCond record) {
        getSqlMapClientTemplate().insert("t7075terminocond.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7075TERMINOCOND
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void insertSelective(T7075TerminoCond record) {
        getSqlMapClientTemplate().insert("t7075terminocond.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7075TERMINOCOND
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public T7075TerminoCond selectByPrimaryKey(BigDecimal codTerycon) {
        T7075TerminoCond key = new T7075TerminoCond();
        key.setCodTerycon(codTerycon);
        T7075TerminoCond record = (T7075TerminoCond) getSqlMapClientTemplate().queryForObject("t7075terminocond.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7075TERMINOCOND
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int updateByPrimaryKeySelective(T7075TerminoCond record) {
        int rows = getSqlMapClientTemplate().update("t7075terminocond.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7075TERMINOCOND
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int updateByPrimaryKey(T7075TerminoCond record) {
        int rows = getSqlMapClientTemplate().update("t7075terminocond.updateByPrimaryKey", record);
        return rows;
    }

    public List<T7075TerminoCond> listByParameter(T7075TerminoCond param) {
        List<T7075TerminoCond> list = (List<T7075TerminoCond>) getSqlMapClientTemplate().queryForList("t7075terminocond.listByParameter", param);
        return list;
    }
}