package pe.gob.sunat.recurso2.administracion.siga.firma.model.dao.ibatis;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.sunat.recurso2.administracion.siga.firma.model.bean.T7076DelegacFirma;
import pe.gob.sunat.recurso2.administracion.siga.firma.model.dao.T7076DelegacFirmaDAO;

public class SqlMapT7076DelegacFirmaDAOImpl extends SqlMapClientDaoSupport implements T7076DelegacFirmaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7076DELEGACFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */

    public SqlMapT7076DelegacFirmaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7076DELEGACFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int deleteByPrimaryKey(BigDecimal codDelegacion) throws DataAccessException{
        T7076DelegacFirma key = new T7076DelegacFirma();
        key.setCodDelegacion(codDelegacion);
        int rows = getSqlMapClientTemplate().delete("t7076delegacfirma.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7076DELEGACFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void insert(T7076DelegacFirma record) throws DataAccessException {
        getSqlMapClientTemplate().insert("t7076delegacfirma.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7076DELEGACFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void insertSelective(T7076DelegacFirma record) throws DataAccessException{
        getSqlMapClientTemplate().insert("t7076delegacfirma.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7076DELEGACFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public T7076DelegacFirma selectByPrimaryKey(BigDecimal codDelegacion) throws DataAccessException{
        T7076DelegacFirma key = new T7076DelegacFirma();
        key.setCodDelegacion(codDelegacion);
        T7076DelegacFirma record = (T7076DelegacFirma) getSqlMapClientTemplate().queryForObject("t7076delegacfirma.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7076DELEGACFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int updateByPrimaryKeySelective(T7076DelegacFirma record) throws DataAccessException{
        int rows = getSqlMapClientTemplate().update("t7076delegacfirma.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7076DELEGACFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public int updateByPrimaryKey(T7076DelegacFirma record) throws DataAccessException{
        int rows = getSqlMapClientTemplate().update("t7076delegacfirma.updateByPrimaryKey", record);
        return rows;
    }

    public List<T7076DelegacFirma> listByParameter(T7076DelegacFirma param) {
        List<T7076DelegacFirma> list = (List<T7076DelegacFirma>) getSqlMapClientTemplate().queryForList("t7076delegacfirma.listByParameter", param);
        return list;
    }
}