package pe.gob.sunat.recurso2.administracion.siga.firma.model.bean;

import java.math.BigDecimal;
import java.util.Date;

public class T7073FirmaElectron {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.COD_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codFirma;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.COD_TERYCON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private BigDecimal codTerycon;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.COD_FIRMANTE
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codFirmante;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.FEC_AFILIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecAfilia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.FEC_DESAFILIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecDesafilia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.IND_ESTFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String indEstfirma;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecRegis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUsuregis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String dirIpusuregis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecModif;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUsumodif;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7073FIRMAELECTRON.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String dirIpusumodif;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.COD_FIRMA
     *
     * @return the value of T7073FIRMAELECTRON.COD_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodFirma() {
        return codFirma;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.COD_FIRMA
     *
     * @param codFirma the value for T7073FIRMAELECTRON.COD_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodFirma(String codFirma) {
        this.codFirma = codFirma == null ? null : codFirma.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.COD_TERYCON
     *
     * @return the value of T7073FIRMAELECTRON.COD_TERYCON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public BigDecimal getCodTerycon() {
        return codTerycon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.COD_TERYCON
     *
     * @param codTerycon the value for T7073FIRMAELECTRON.COD_TERYCON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodTerycon(BigDecimal codTerycon) {
        this.codTerycon = codTerycon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.COD_FIRMANTE
     *
     * @return the value of T7073FIRMAELECTRON.COD_FIRMANTE
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodFirmante() {
        return codFirmante;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.COD_FIRMANTE
     *
     * @param codFirmante the value for T7073FIRMAELECTRON.COD_FIRMANTE
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodFirmante(String codFirmante) {
        this.codFirmante = codFirmante == null ? null : codFirmante.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.FEC_AFILIA
     *
     * @return the value of T7073FIRMAELECTRON.FEC_AFILIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecAfilia() {
        return fecAfilia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.FEC_AFILIA
     *
     * @param fecAfilia the value for T7073FIRMAELECTRON.FEC_AFILIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecAfilia(Date fecAfilia) {
        this.fecAfilia = fecAfilia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.FEC_DESAFILIA
     *
     * @return the value of T7073FIRMAELECTRON.FEC_DESAFILIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecDesafilia() {
        return fecDesafilia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.FEC_DESAFILIA
     *
     * @param fecDesafilia the value for T7073FIRMAELECTRON.FEC_DESAFILIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecDesafilia(Date fecDesafilia) {
        this.fecDesafilia = fecDesafilia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.IND_ESTFIRMA
     *
     * @return the value of T7073FIRMAELECTRON.IND_ESTFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getIndEstfirma() {
        return indEstfirma;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.IND_ESTFIRMA
     *
     * @param indEstfirma the value for T7073FIRMAELECTRON.IND_ESTFIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setIndEstfirma(String indEstfirma) {
        this.indEstfirma = indEstfirma == null ? null : indEstfirma.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.FEC_REGIS
     *
     * @return the value of T7073FIRMAELECTRON.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecRegis() {
        return fecRegis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.FEC_REGIS
     *
     * @param fecRegis the value for T7073FIRMAELECTRON.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecRegis(Date fecRegis) {
        this.fecRegis = fecRegis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.COD_USUREGIS
     *
     * @return the value of T7073FIRMAELECTRON.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUsuregis() {
        return codUsuregis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.COD_USUREGIS
     *
     * @param codUsuregis the value for T7073FIRMAELECTRON.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUsuregis(String codUsuregis) {
        this.codUsuregis = codUsuregis == null ? null : codUsuregis.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.DIR_IPUSUREGIS
     *
     * @return the value of T7073FIRMAELECTRON.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getDirIpusuregis() {
        return dirIpusuregis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.DIR_IPUSUREGIS
     *
     * @param dirIpusuregis the value for T7073FIRMAELECTRON.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setDirIpusuregis(String dirIpusuregis) {
        this.dirIpusuregis = dirIpusuregis == null ? null : dirIpusuregis.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.FEC_MODIF
     *
     * @return the value of T7073FIRMAELECTRON.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecModif() {
        return fecModif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.FEC_MODIF
     *
     * @param fecModif the value for T7073FIRMAELECTRON.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecModif(Date fecModif) {
        this.fecModif = fecModif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.COD_USUMODIF
     *
     * @return the value of T7073FIRMAELECTRON.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUsumodif() {
        return codUsumodif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.COD_USUMODIF
     *
     * @param codUsumodif the value for T7073FIRMAELECTRON.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUsumodif(String codUsumodif) {
        this.codUsumodif = codUsumodif == null ? null : codUsumodif.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7073FIRMAELECTRON.DIR_IPUSUMODIF
     *
     * @return the value of T7073FIRMAELECTRON.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getDirIpusumodif() {
        return dirIpusumodif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7073FIRMAELECTRON.DIR_IPUSUMODIF
     *
     * @param dirIpusumodif the value for T7073FIRMAELECTRON.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setDirIpusumodif(String dirIpusumodif) {
        this.dirIpusumodif = dirIpusumodif == null ? null : dirIpusumodif.trim();
    }
}