package pe.gob.sunat.recurso2.administracion.siga.firma.model.bean;

import java.math.BigDecimal;
import java.util.Date;

public class T7074DocumentoFirm {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_DOCAUT
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private BigDecimal codDocaut;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codFirma;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_TIPDOC
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codTipdoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.NUM_DOCUMENTO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String numDocumento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.NUM__SECUENCIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Short numSecuencia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_DOCSEQ
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private BigDecimal codDocseq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.NUM_VERSION
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Short numVersion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_UUOO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUuoo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_UNNORMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUnnorma;
    
    private String codToken;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.NOM_MODULO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String nomModulo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.NOM_PROCESO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String nomProceso;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.FEC_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecFirma;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.NOM_ARCHIVO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String nomArchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_IDARCHIVO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private BigDecimal codIdarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_USUAUTOR
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUsuautor;
    
    private String codCargtca;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.IND_ESTDOC
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String indEstdoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecRegis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUsuregis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String dirIpusuregis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecModif;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUsumodif;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7074DOCUMENTOFIRM.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String dirIpusumodif;

    private String codNumregalterno;
    private String codCodinivenvl;
    
    private String numeroRegistroAlterno;
    private String nombCortPer;
    private String librElecPer;
    private String unidadOrganizacional;
    private String descDepeTde;
    private String abreviatura;
    private String descCargTca;
    private String descripcionCortaCargo;

    //(INICIO)DPORRASC
    private String desTipoDocumento;
    private String uuooNorma;
    private String descUuooNorma;
    private byte[] arcFirmado; //ARC_FIRMADO
    
	public byte[] getArcFirmado() {
		return arcFirmado;
	}
	public void setArcFirmado(byte[] arcFirmado) {
		this.arcFirmado = arcFirmado;
	}
	public String getUuooNorma() {
		return uuooNorma;
	}
	public String getDescUuooNorma() {
		return descUuooNorma;
	}
	public void setDescUuooNorma(String descUuooNorma) {
		this.descUuooNorma = descUuooNorma;
	}
	public void setUuooNorma(String uuooNorma) {
		this.uuooNorma = uuooNorma;
	}
	public String getDesTipoDocumento() {
		return desTipoDocumento;
	}
	public void setDesTipoDocumento(String desTipoDocumento) {
		this.desTipoDocumento = desTipoDocumento;
	}
	//(FIN DPORRASC)
	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_DOCAUT
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_DOCAUT
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public BigDecimal getCodDocaut() {
        return codDocaut;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_DOCAUT
     *
     * @param codDocaut the value for T7074DOCUMENTOFIRM.COD_DOCAUT
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodDocaut(BigDecimal codDocaut) {
        this.codDocaut = codDocaut;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_FIRMA
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodFirma() {
        return codFirma;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_FIRMA
     *
     * @param codFirma the value for T7074DOCUMENTOFIRM.COD_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodFirma(String codFirma) {
        this.codFirma = codFirma == null ? null : codFirma.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_TIPDOC
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_TIPDOC
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodTipdoc() {
        return codTipdoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_TIPDOC
     *
     * @param codTipdoc the value for T7074DOCUMENTOFIRM.COD_TIPDOC
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodTipdoc(String codTipdoc) {
        this.codTipdoc = codTipdoc == null ? null : codTipdoc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.NUM_DOCUMENTO
     *
     * @return the value of T7074DOCUMENTOFIRM.NUM_DOCUMENTO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getNumDocumento() {
        return numDocumento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.NUM_DOCUMENTO
     *
     * @param numDocumento the value for T7074DOCUMENTOFIRM.NUM_DOCUMENTO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setNumDocumento(String numDocumento) {
        this.numDocumento = numDocumento == null ? null : numDocumento.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.NUM__SECUENCIA
     *
     * @return the value of T7074DOCUMENTOFIRM.NUM__SECUENCIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Short getNumSecuencia() {
        return numSecuencia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.NUM__SECUENCIA
     *
     * @param numSecuencia the value for T7074DOCUMENTOFIRM.NUM__SECUENCIA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setNumSecuencia(Short numSecuencia) {
        this.numSecuencia = numSecuencia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_DOCSEQ
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_DOCSEQ
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public BigDecimal getCodDocseq() {
        return codDocseq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_DOCSEQ
     *
     * @param codDocseq the value for T7074DOCUMENTOFIRM.COD_DOCSEQ
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodDocseq(BigDecimal codDocseq) {
        this.codDocseq = codDocseq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.NUM_VERSION
     *
     * @return the value of T7074DOCUMENTOFIRM.NUM_VERSION
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Short getNumVersion() {
        return numVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.NUM_VERSION
     *
     * @param numVersion the value for T7074DOCUMENTOFIRM.NUM_VERSION
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setNumVersion(Short numVersion) {
        this.numVersion = numVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_UUOO
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_UUOO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUuoo() {
        return codUuoo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_UUOO
     *
     * @param codUuoo the value for T7074DOCUMENTOFIRM.COD_UUOO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUuoo(String codUuoo) {
        this.codUuoo = codUuoo == null ? null : codUuoo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_UNNORMA
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_UNNORMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUnnorma() {
        return codUnnorma;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_UNNORMA
     *
     * @param codUnnorma the value for T7074DOCUMENTOFIRM.COD_UNNORMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUnnorma(String codUnnorma) {
        this.codUnnorma = codUnnorma == null ? null : codUnnorma.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.NOM_MODULO
     *
     * @return the value of T7074DOCUMENTOFIRM.NOM_MODULO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getNomModulo() {
        return nomModulo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.NOM_MODULO
     *
     * @param nomModulo the value for T7074DOCUMENTOFIRM.NOM_MODULO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setNomModulo(String nomModulo) {
        this.nomModulo = nomModulo == null ? null : nomModulo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.NOM_PROCESO
     *
     * @return the value of T7074DOCUMENTOFIRM.NOM_PROCESO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getNomProceso() {
        return nomProceso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.NOM_PROCESO
     *
     * @param nomProceso the value for T7074DOCUMENTOFIRM.NOM_PROCESO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setNomProceso(String nomProceso) {
        this.nomProceso = nomProceso == null ? null : nomProceso.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.FEC_FIRMA
     *
     * @return the value of T7074DOCUMENTOFIRM.FEC_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecFirma() {
        return fecFirma;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.FEC_FIRMA
     *
     * @param fecFirma the value for T7074DOCUMENTOFIRM.FEC_FIRMA
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecFirma(Date fecFirma) {
        this.fecFirma = fecFirma;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.NOM_ARCHIVO
     *
     * @return the value of T7074DOCUMENTOFIRM.NOM_ARCHIVO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getNomArchivo() {
        return nomArchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.NOM_ARCHIVO
     *
     * @param nomArchivo the value for T7074DOCUMENTOFIRM.NOM_ARCHIVO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setNomArchivo(String nomArchivo) {
        this.nomArchivo = nomArchivo == null ? null : nomArchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_IDARCHIVO
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_IDARCHIVO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public BigDecimal getCodIdarchivo() {
        return codIdarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_IDARCHIVO
     *
     * @param codIdarchivo the value for T7074DOCUMENTOFIRM.COD_IDARCHIVO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodIdarchivo(BigDecimal codIdarchivo) {
        this.codIdarchivo = codIdarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_USUAUTOR
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_USUAUTOR
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUsuautor() {
        return codUsuautor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_USUAUTOR
     *
     * @param codUsuautor the value for T7074DOCUMENTOFIRM.COD_USUAUTOR
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUsuautor(String codUsuautor) {
        this.codUsuautor = codUsuautor == null ? null : codUsuautor.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.IND_ESTDOC
     *
     * @return the value of T7074DOCUMENTOFIRM.IND_ESTDOC
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getIndEstdoc() {
        return indEstdoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.IND_ESTDOC
     *
     * @param indEstdoc the value for T7074DOCUMENTOFIRM.IND_ESTDOC
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setIndEstdoc(String indEstdoc) {
        this.indEstdoc = indEstdoc == null ? null : indEstdoc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.FEC_REGIS
     *
     * @return the value of T7074DOCUMENTOFIRM.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecRegis() {
        return fecRegis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.FEC_REGIS
     *
     * @param fecRegis the value for T7074DOCUMENTOFIRM.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecRegis(Date fecRegis) {
        this.fecRegis = fecRegis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_USUREGIS
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUsuregis() {
        return codUsuregis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_USUREGIS
     *
     * @param codUsuregis the value for T7074DOCUMENTOFIRM.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUsuregis(String codUsuregis) {
        this.codUsuregis = codUsuregis == null ? null : codUsuregis.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.DIR_IPUSUREGIS
     *
     * @return the value of T7074DOCUMENTOFIRM.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getDirIpusuregis() {
        return dirIpusuregis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.DIR_IPUSUREGIS
     *
     * @param dirIpusuregis the value for T7074DOCUMENTOFIRM.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setDirIpusuregis(String dirIpusuregis) {
        this.dirIpusuregis = dirIpusuregis == null ? null : dirIpusuregis.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.FEC_MODIF
     *
     * @return the value of T7074DOCUMENTOFIRM.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecModif() {
        return fecModif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.FEC_MODIF
     *
     * @param fecModif the value for T7074DOCUMENTOFIRM.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecModif(Date fecModif) {
        this.fecModif = fecModif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.COD_USUMODIF
     *
     * @return the value of T7074DOCUMENTOFIRM.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUsumodif() {
        return codUsumodif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.COD_USUMODIF
     *
     * @param codUsumodif the value for T7074DOCUMENTOFIRM.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUsumodif(String codUsumodif) {
        this.codUsumodif = codUsumodif == null ? null : codUsumodif.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7074DOCUMENTOFIRM.DIR_IPUSUMODIF
     *
     * @return the value of T7074DOCUMENTOFIRM.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getDirIpusumodif() {
        return dirIpusumodif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7074DOCUMENTOFIRM.DIR_IPUSUMODIF
     *
     * @param dirIpusumodif the value for T7074DOCUMENTOFIRM.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setDirIpusumodif(String dirIpusumodif) {
        this.dirIpusumodif = dirIpusumodif == null ? null : dirIpusumodif.trim();
    }

	public String getNumeroRegistroAlterno() {
		return numeroRegistroAlterno;
	}

	public void setNumeroRegistroAlterno(String numeroRegistroAlterno) {
		this.numeroRegistroAlterno = numeroRegistroAlterno;
	}

	public String getNombCortPer() {
		return nombCortPer;
	}

	public void setNombCortPer(String nombCortPer) {
		this.nombCortPer = nombCortPer;
	}

	public String getUnidadOrganizacional() {
		return unidadOrganizacional;
	}

	public void setUnidadOrganizacional(String unidadOrganizacional) {
		this.unidadOrganizacional = unidadOrganizacional;
	}

	public String getDescDepeTde() {
		return descDepeTde;
	}

	public void setDescDepeTde(String descDepeTde) {
		this.descDepeTde = descDepeTde;
	}

	public String getAbreviatura() {
		return abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	public void setCodToken(String codToken) {
		this.codToken = codToken;
	}

	public String getCodToken() {
		return codToken;
	}

	public void setCodCargtca(String codCargtca) {
		this.codCargtca = codCargtca;
	}

	public String getCodCargtca() {
		return codCargtca;
	}

	public void setDescCargTca(String descCargTca) {
		this.descCargTca = descCargTca;
	}

	public String getDescCargTca() {
		return descCargTca;
	}

	public void setDescripcionCortaCargo(String descripcionCortaCargo) {
		this.descripcionCortaCargo = descripcionCortaCargo;
	}

	public String getDescripcionCortaCargo() {
		return descripcionCortaCargo;
	}

	public void setLibrElecPer(String librElecPer) {
		this.librElecPer = librElecPer;
	}

	public String getLibrElecPer() {
		return librElecPer;
	}
	public void setCodNumregalterno(String codNumregalterno) {
		this.codNumregalterno = codNumregalterno;
	}
	public String getCodNumregalterno() {
		return codNumregalterno;
	}
	public void setCodCodinivenvl(String codCodinivenvl) {
		this.codCodinivenvl = codCodinivenvl;
	}
	public String getCodCodinivenvl() {
		return codCodinivenvl;
	}
	
}