package pe.gob.sunat.recurso2.administracion.siga.firma.model.bean;

import java.math.BigDecimal;
import java.util.Date;

public class T7075TerminoCond {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.COD_TERYCON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private BigDecimal codTerycon;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.COD_TIPO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codTipo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.NUM_VERSION
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Integer numVersion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.DES_TERMINOS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String desTerminos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.IND_ESTTERMINO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String indEsttermino;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecRegis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUsuregis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String dirIpusuregis;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private Date fecModif;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String codUsumodif;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T7075TERMINOCOND.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    private String dirIpusumodif;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.COD_TERYCON
     *
     * @return the value of T7075TERMINOCOND.COD_TERYCON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public BigDecimal getCodTerycon() {
        return codTerycon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.COD_TERYCON
     *
     * @param codTerycon the value for T7075TERMINOCOND.COD_TERYCON
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodTerycon(BigDecimal codTerycon) {
        this.codTerycon = codTerycon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.COD_TIPO
     *
     * @return the value of T7075TERMINOCOND.COD_TIPO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodTipo() {
        return codTipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.COD_TIPO
     *
     * @param codTipo the value for T7075TERMINOCOND.COD_TIPO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodTipo(String codTipo) {
        this.codTipo = codTipo == null ? null : codTipo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.NUM_VERSION
     *
     * @return the value of T7075TERMINOCOND.NUM_VERSION
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Integer getNumVersion() {
        return numVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.NUM_VERSION
     *
     * @param numVersion the value for T7075TERMINOCOND.NUM_VERSION
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setNumVersion(Integer numVersion) {
        this.numVersion = numVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.DES_TERMINOS
     *
     * @return the value of T7075TERMINOCOND.DES_TERMINOS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getDesTerminos() {
        return desTerminos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.DES_TERMINOS
     *
     * @param desTerminos the value for T7075TERMINOCOND.DES_TERMINOS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setDesTerminos(String desTerminos) {
        this.desTerminos = desTerminos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.IND_ESTTERMINO
     *
     * @return the value of T7075TERMINOCOND.IND_ESTTERMINO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getIndEsttermino() {
        return indEsttermino;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.IND_ESTTERMINO
     *
     * @param indEsttermino the value for T7075TERMINOCOND.IND_ESTTERMINO
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setIndEsttermino(String indEsttermino) {
        this.indEsttermino = indEsttermino == null ? null : indEsttermino.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.FEC_REGIS
     *
     * @return the value of T7075TERMINOCOND.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecRegis() {
        return fecRegis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.FEC_REGIS
     *
     * @param fecRegis the value for T7075TERMINOCOND.FEC_REGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecRegis(Date fecRegis) {
        this.fecRegis = fecRegis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.COD_USUREGIS
     *
     * @return the value of T7075TERMINOCOND.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUsuregis() {
        return codUsuregis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.COD_USUREGIS
     *
     * @param codUsuregis the value for T7075TERMINOCOND.COD_USUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUsuregis(String codUsuregis) {
        this.codUsuregis = codUsuregis == null ? null : codUsuregis.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.DIR_IPUSUREGIS
     *
     * @return the value of T7075TERMINOCOND.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getDirIpusuregis() {
        return dirIpusuregis;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.DIR_IPUSUREGIS
     *
     * @param dirIpusuregis the value for T7075TERMINOCOND.DIR_IPUSUREGIS
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setDirIpusuregis(String dirIpusuregis) {
        this.dirIpusuregis = dirIpusuregis == null ? null : dirIpusuregis.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.FEC_MODIF
     *
     * @return the value of T7075TERMINOCOND.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public Date getFecModif() {
        return fecModif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.FEC_MODIF
     *
     * @param fecModif the value for T7075TERMINOCOND.FEC_MODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setFecModif(Date fecModif) {
        this.fecModif = fecModif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.COD_USUMODIF
     *
     * @return the value of T7075TERMINOCOND.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getCodUsumodif() {
        return codUsumodif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.COD_USUMODIF
     *
     * @param codUsumodif the value for T7075TERMINOCOND.COD_USUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setCodUsumodif(String codUsumodif) {
        this.codUsumodif = codUsumodif == null ? null : codUsumodif.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T7075TERMINOCOND.DIR_IPUSUMODIF
     *
     * @return the value of T7075TERMINOCOND.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public String getDirIpusumodif() {
        return dirIpusumodif;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T7075TERMINOCOND.DIR_IPUSUMODIF
     *
     * @param dirIpusumodif the value for T7075TERMINOCOND.DIR_IPUSUMODIF
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    public void setDirIpusumodif(String dirIpusumodif) {
        this.dirIpusumodif = dirIpusumodif == null ? null : dirIpusumodif.trim();
    }
}