package pe.gob.sunat.recurso2.administracion.siga.registro.model.bean;

import java.util.Date;

public class Ddp {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_lllttt
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpLllttt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_secuen
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Long ddpSecuen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_nombre
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpNombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_numruc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpNumruc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_numreg
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpNumreg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_tpoemp
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpTpoemp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_tamano
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpTamano;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_identi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpIdenti;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_ciiu
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpCiiu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_ubigeo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpUbigeo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_nomvia
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpNomvia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_numer1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpNumer1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_inter1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpInter1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_nomzon
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpNomzon;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_refer1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpRefer1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_flag22
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpFlag22;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_estado
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpEstado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_fecalt
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date ddpFecalt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_fecbaj
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date ddpFecbaj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_tipvia
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpTipvia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_tipzon
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpTipzon;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_doble
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpDoble;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_mclase
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpMclase;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_reacti
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpReacti;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddpUserna;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDP.ddp_fecact
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date ddpFecact;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_lllttt
     *
     * @return the value of VWDDP.ddp_lllttt
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpLllttt() {
        return ddpLllttt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_lllttt
     *
     * @param ddpLllttt the value for VWDDP.ddp_lllttt
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpLllttt(String ddpLllttt) {
        this.ddpLllttt = ddpLllttt == null ? null : ddpLllttt.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_secuen
     *
     * @return the value of VWDDP.ddp_secuen
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Long getDdpSecuen() {
        return ddpSecuen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_secuen
     *
     * @param ddpSecuen the value for VWDDP.ddp_secuen
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpSecuen(Long ddpSecuen) {
        this.ddpSecuen = ddpSecuen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_nombre
     *
     * @return the value of VWDDP.ddp_nombre
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpNombre() {
        return ddpNombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_nombre
     *
     * @param ddpNombre the value for VWDDP.ddp_nombre
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpNombre(String ddpNombre) {
        this.ddpNombre = ddpNombre == null ? null : ddpNombre.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_numruc
     *
     * @return the value of VWDDP.ddp_numruc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpNumruc() {
        return ddpNumruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_numruc
     *
     * @param ddpNumruc the value for VWDDP.ddp_numruc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpNumruc(String ddpNumruc) {
        this.ddpNumruc = ddpNumruc == null ? null : ddpNumruc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_numreg
     *
     * @return the value of VWDDP.ddp_numreg
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpNumreg() {
        return ddpNumreg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_numreg
     *
     * @param ddpNumreg the value for VWDDP.ddp_numreg
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpNumreg(String ddpNumreg) {
        this.ddpNumreg = ddpNumreg == null ? null : ddpNumreg.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_tpoemp
     *
     * @return the value of VWDDP.ddp_tpoemp
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpTpoemp() {
        return ddpTpoemp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_tpoemp
     *
     * @param ddpTpoemp the value for VWDDP.ddp_tpoemp
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpTpoemp(String ddpTpoemp) {
        this.ddpTpoemp = ddpTpoemp == null ? null : ddpTpoemp.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_tamano
     *
     * @return the value of VWDDP.ddp_tamano
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpTamano() {
        return ddpTamano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_tamano
     *
     * @param ddpTamano the value for VWDDP.ddp_tamano
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpTamano(String ddpTamano) {
        this.ddpTamano = ddpTamano == null ? null : ddpTamano.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_identi
     *
     * @return the value of VWDDP.ddp_identi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpIdenti() {
        return ddpIdenti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_identi
     *
     * @param ddpIdenti the value for VWDDP.ddp_identi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpIdenti(String ddpIdenti) {
        this.ddpIdenti = ddpIdenti == null ? null : ddpIdenti.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_ciiu
     *
     * @return the value of VWDDP.ddp_ciiu
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpCiiu() {
        return ddpCiiu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_ciiu
     *
     * @param ddpCiiu the value for VWDDP.ddp_ciiu
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpCiiu(String ddpCiiu) {
        this.ddpCiiu = ddpCiiu == null ? null : ddpCiiu.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_ubigeo
     *
     * @return the value of VWDDP.ddp_ubigeo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpUbigeo() {
        return ddpUbigeo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_ubigeo
     *
     * @param ddpUbigeo the value for VWDDP.ddp_ubigeo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpUbigeo(String ddpUbigeo) {
        this.ddpUbigeo = ddpUbigeo == null ? null : ddpUbigeo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_nomvia
     *
     * @return the value of VWDDP.ddp_nomvia
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpNomvia() {
        return ddpNomvia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_nomvia
     *
     * @param ddpNomvia the value for VWDDP.ddp_nomvia
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpNomvia(String ddpNomvia) {
        this.ddpNomvia = ddpNomvia == null ? null : ddpNomvia.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_numer1
     *
     * @return the value of VWDDP.ddp_numer1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpNumer1() {
        return ddpNumer1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_numer1
     *
     * @param ddpNumer1 the value for VWDDP.ddp_numer1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpNumer1(String ddpNumer1) {
        this.ddpNumer1 = ddpNumer1 == null ? null : ddpNumer1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_inter1
     *
     * @return the value of VWDDP.ddp_inter1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpInter1() {
        return ddpInter1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_inter1
     *
     * @param ddpInter1 the value for VWDDP.ddp_inter1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpInter1(String ddpInter1) {
        this.ddpInter1 = ddpInter1 == null ? null : ddpInter1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_nomzon
     *
     * @return the value of VWDDP.ddp_nomzon
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpNomzon() {
        return ddpNomzon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_nomzon
     *
     * @param ddpNomzon the value for VWDDP.ddp_nomzon
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpNomzon(String ddpNomzon) {
        this.ddpNomzon = ddpNomzon == null ? null : ddpNomzon.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_refer1
     *
     * @return the value of VWDDP.ddp_refer1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpRefer1() {
        return ddpRefer1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_refer1
     *
     * @param ddpRefer1 the value for VWDDP.ddp_refer1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpRefer1(String ddpRefer1) {
        this.ddpRefer1 = ddpRefer1 == null ? null : ddpRefer1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_flag22
     *
     * @return the value of VWDDP.ddp_flag22
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpFlag22() {
        return ddpFlag22;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_flag22
     *
     * @param ddpFlag22 the value for VWDDP.ddp_flag22
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpFlag22(String ddpFlag22) {
        this.ddpFlag22 = ddpFlag22 == null ? null : ddpFlag22.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_estado
     *
     * @return the value of VWDDP.ddp_estado
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpEstado() {
        return ddpEstado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_estado
     *
     * @param ddpEstado the value for VWDDP.ddp_estado
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpEstado(String ddpEstado) {
        this.ddpEstado = ddpEstado == null ? null : ddpEstado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_fecalt
     *
     * @return the value of VWDDP.ddp_fecalt
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getDdpFecalt() {
        return ddpFecalt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_fecalt
     *
     * @param ddpFecalt the value for VWDDP.ddp_fecalt
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpFecalt(Date ddpFecalt) {
        this.ddpFecalt = ddpFecalt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_fecbaj
     *
     * @return the value of VWDDP.ddp_fecbaj
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getDdpFecbaj() {
        return ddpFecbaj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_fecbaj
     *
     * @param ddpFecbaj the value for VWDDP.ddp_fecbaj
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpFecbaj(Date ddpFecbaj) {
        this.ddpFecbaj = ddpFecbaj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_tipvia
     *
     * @return the value of VWDDP.ddp_tipvia
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpTipvia() {
        return ddpTipvia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_tipvia
     *
     * @param ddpTipvia the value for VWDDP.ddp_tipvia
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpTipvia(String ddpTipvia) {
        this.ddpTipvia = ddpTipvia == null ? null : ddpTipvia.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_tipzon
     *
     * @return the value of VWDDP.ddp_tipzon
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpTipzon() {
        return ddpTipzon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_tipzon
     *
     * @param ddpTipzon the value for VWDDP.ddp_tipzon
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpTipzon(String ddpTipzon) {
        this.ddpTipzon = ddpTipzon == null ? null : ddpTipzon.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_doble
     *
     * @return the value of VWDDP.ddp_doble
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpDoble() {
        return ddpDoble;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_doble
     *
     * @param ddpDoble the value for VWDDP.ddp_doble
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpDoble(String ddpDoble) {
        this.ddpDoble = ddpDoble == null ? null : ddpDoble.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_mclase
     *
     * @return the value of VWDDP.ddp_mclase
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpMclase() {
        return ddpMclase;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_mclase
     *
     * @param ddpMclase the value for VWDDP.ddp_mclase
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpMclase(String ddpMclase) {
        this.ddpMclase = ddpMclase == null ? null : ddpMclase.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_reacti
     *
     * @return the value of VWDDP.ddp_reacti
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpReacti() {
        return ddpReacti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_reacti
     *
     * @param ddpReacti the value for VWDDP.ddp_reacti
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpReacti(String ddpReacti) {
        this.ddpReacti = ddpReacti == null ? null : ddpReacti.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_userna
     *
     * @return the value of VWDDP.ddp_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdpUserna() {
        return ddpUserna;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_userna
     *
     * @param ddpUserna the value for VWDDP.ddp_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpUserna(String ddpUserna) {
        this.ddpUserna = ddpUserna == null ? null : ddpUserna.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDP.ddp_fecact
     *
     * @return the value of VWDDP.ddp_fecact
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getDdpFecact() {
        return ddpFecact;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDP.ddp_fecact
     *
     * @param ddpFecact the value for VWDDP.ddp_fecact
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdpFecact(Date ddpFecact) {
        this.ddpFecact = ddpFecact;
    }
}