package pe.gob.sunat.recurso2.administracion.siga.registro.model.bean;

import java.util.Date;

public class Dds {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_numruc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsNumruc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_telef1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsTelef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_telef2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsTelef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_telef3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsTelef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_numfax
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsNumfax;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_pasapo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsPasapo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_licenc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsLicenc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_contab
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsContab;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_factur
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsFactur;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_consti
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date ddsConsti;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_ficha
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsFicha;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_inicio
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date ddsInicio;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_cierre
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsCierre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_fecven
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date ddsFecven;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_califi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsCalifi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_domici
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsDomici;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_orient
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsOrient;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_patron
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsPatron;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_ejempl
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsEjempl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_motemi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsMotemi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_nomcom
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsNomcom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_aparta
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsAparta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_paispa
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsPaispa;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_nfolio
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsNfolio;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_asient
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsAsient;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_comext
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsComext;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_centro
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsCentro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_motbaj
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsMotbaj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_docide
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsDocide;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_nrodoc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsNrodoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_sexo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsSexo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_nacion
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsNacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_fecnac
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date ddsFecnac;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String ddsUserna;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWDDS.dds_fecact
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date ddsFecact;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_numruc
     *
     * @return the value of VWDDS.dds_numruc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsNumruc() {
        return ddsNumruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_numruc
     *
     * @param ddsNumruc the value for VWDDS.dds_numruc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsNumruc(String ddsNumruc) {
        this.ddsNumruc = ddsNumruc == null ? null : ddsNumruc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_telef1
     *
     * @return the value of VWDDS.dds_telef1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsTelef1() {
        return ddsTelef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_telef1
     *
     * @param ddsTelef1 the value for VWDDS.dds_telef1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsTelef1(String ddsTelef1) {
        this.ddsTelef1 = ddsTelef1 == null ? null : ddsTelef1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_telef2
     *
     * @return the value of VWDDS.dds_telef2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsTelef2() {
        return ddsTelef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_telef2
     *
     * @param ddsTelef2 the value for VWDDS.dds_telef2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsTelef2(String ddsTelef2) {
        this.ddsTelef2 = ddsTelef2 == null ? null : ddsTelef2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_telef3
     *
     * @return the value of VWDDS.dds_telef3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsTelef3() {
        return ddsTelef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_telef3
     *
     * @param ddsTelef3 the value for VWDDS.dds_telef3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsTelef3(String ddsTelef3) {
        this.ddsTelef3 = ddsTelef3 == null ? null : ddsTelef3.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_numfax
     *
     * @return the value of VWDDS.dds_numfax
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsNumfax() {
        return ddsNumfax;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_numfax
     *
     * @param ddsNumfax the value for VWDDS.dds_numfax
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsNumfax(String ddsNumfax) {
        this.ddsNumfax = ddsNumfax == null ? null : ddsNumfax.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_pasapo
     *
     * @return the value of VWDDS.dds_pasapo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsPasapo() {
        return ddsPasapo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_pasapo
     *
     * @param ddsPasapo the value for VWDDS.dds_pasapo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsPasapo(String ddsPasapo) {
        this.ddsPasapo = ddsPasapo == null ? null : ddsPasapo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_licenc
     *
     * @return the value of VWDDS.dds_licenc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsLicenc() {
        return ddsLicenc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_licenc
     *
     * @param ddsLicenc the value for VWDDS.dds_licenc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsLicenc(String ddsLicenc) {
        this.ddsLicenc = ddsLicenc == null ? null : ddsLicenc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_contab
     *
     * @return the value of VWDDS.dds_contab
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsContab() {
        return ddsContab;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_contab
     *
     * @param ddsContab the value for VWDDS.dds_contab
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsContab(String ddsContab) {
        this.ddsContab = ddsContab == null ? null : ddsContab.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_factur
     *
     * @return the value of VWDDS.dds_factur
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsFactur() {
        return ddsFactur;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_factur
     *
     * @param ddsFactur the value for VWDDS.dds_factur
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsFactur(String ddsFactur) {
        this.ddsFactur = ddsFactur == null ? null : ddsFactur.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_consti
     *
     * @return the value of VWDDS.dds_consti
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getDdsConsti() {
        return ddsConsti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_consti
     *
     * @param ddsConsti the value for VWDDS.dds_consti
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsConsti(Date ddsConsti) {
        this.ddsConsti = ddsConsti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_ficha
     *
     * @return the value of VWDDS.dds_ficha
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsFicha() {
        return ddsFicha;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_ficha
     *
     * @param ddsFicha the value for VWDDS.dds_ficha
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsFicha(String ddsFicha) {
        this.ddsFicha = ddsFicha == null ? null : ddsFicha.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_inicio
     *
     * @return the value of VWDDS.dds_inicio
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getDdsInicio() {
        return ddsInicio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_inicio
     *
     * @param ddsInicio the value for VWDDS.dds_inicio
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsInicio(Date ddsInicio) {
        this.ddsInicio = ddsInicio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_cierre
     *
     * @return the value of VWDDS.dds_cierre
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsCierre() {
        return ddsCierre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_cierre
     *
     * @param ddsCierre the value for VWDDS.dds_cierre
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsCierre(String ddsCierre) {
        this.ddsCierre = ddsCierre == null ? null : ddsCierre.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_fecven
     *
     * @return the value of VWDDS.dds_fecven
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getDdsFecven() {
        return ddsFecven;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_fecven
     *
     * @param ddsFecven the value for VWDDS.dds_fecven
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsFecven(Date ddsFecven) {
        this.ddsFecven = ddsFecven;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_califi
     *
     * @return the value of VWDDS.dds_califi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsCalifi() {
        return ddsCalifi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_califi
     *
     * @param ddsCalifi the value for VWDDS.dds_califi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsCalifi(String ddsCalifi) {
        this.ddsCalifi = ddsCalifi == null ? null : ddsCalifi.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_domici
     *
     * @return the value of VWDDS.dds_domici
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsDomici() {
        return ddsDomici;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_domici
     *
     * @param ddsDomici the value for VWDDS.dds_domici
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsDomici(String ddsDomici) {
        this.ddsDomici = ddsDomici == null ? null : ddsDomici.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_orient
     *
     * @return the value of VWDDS.dds_orient
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsOrient() {
        return ddsOrient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_orient
     *
     * @param ddsOrient the value for VWDDS.dds_orient
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsOrient(String ddsOrient) {
        this.ddsOrient = ddsOrient == null ? null : ddsOrient.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_patron
     *
     * @return the value of VWDDS.dds_patron
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsPatron() {
        return ddsPatron;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_patron
     *
     * @param ddsPatron the value for VWDDS.dds_patron
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsPatron(String ddsPatron) {
        this.ddsPatron = ddsPatron == null ? null : ddsPatron.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_ejempl
     *
     * @return the value of VWDDS.dds_ejempl
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsEjempl() {
        return ddsEjempl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_ejempl
     *
     * @param ddsEjempl the value for VWDDS.dds_ejempl
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsEjempl(String ddsEjempl) {
        this.ddsEjempl = ddsEjempl == null ? null : ddsEjempl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_motemi
     *
     * @return the value of VWDDS.dds_motemi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsMotemi() {
        return ddsMotemi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_motemi
     *
     * @param ddsMotemi the value for VWDDS.dds_motemi
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsMotemi(String ddsMotemi) {
        this.ddsMotemi = ddsMotemi == null ? null : ddsMotemi.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_nomcom
     *
     * @return the value of VWDDS.dds_nomcom
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsNomcom() {
        return ddsNomcom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_nomcom
     *
     * @param ddsNomcom the value for VWDDS.dds_nomcom
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsNomcom(String ddsNomcom) {
        this.ddsNomcom = ddsNomcom == null ? null : ddsNomcom.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_aparta
     *
     * @return the value of VWDDS.dds_aparta
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsAparta() {
        return ddsAparta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_aparta
     *
     * @param ddsAparta the value for VWDDS.dds_aparta
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsAparta(String ddsAparta) {
        this.ddsAparta = ddsAparta == null ? null : ddsAparta.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_paispa
     *
     * @return the value of VWDDS.dds_paispa
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsPaispa() {
        return ddsPaispa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_paispa
     *
     * @param ddsPaispa the value for VWDDS.dds_paispa
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsPaispa(String ddsPaispa) {
        this.ddsPaispa = ddsPaispa == null ? null : ddsPaispa.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_nfolio
     *
     * @return the value of VWDDS.dds_nfolio
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsNfolio() {
        return ddsNfolio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_nfolio
     *
     * @param ddsNfolio the value for VWDDS.dds_nfolio
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsNfolio(String ddsNfolio) {
        this.ddsNfolio = ddsNfolio == null ? null : ddsNfolio.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_asient
     *
     * @return the value of VWDDS.dds_asient
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsAsient() {
        return ddsAsient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_asient
     *
     * @param ddsAsient the value for VWDDS.dds_asient
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsAsient(String ddsAsient) {
        this.ddsAsient = ddsAsient == null ? null : ddsAsient.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_comext
     *
     * @return the value of VWDDS.dds_comext
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsComext() {
        return ddsComext;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_comext
     *
     * @param ddsComext the value for VWDDS.dds_comext
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsComext(String ddsComext) {
        this.ddsComext = ddsComext == null ? null : ddsComext.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_centro
     *
     * @return the value of VWDDS.dds_centro
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsCentro() {
        return ddsCentro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_centro
     *
     * @param ddsCentro the value for VWDDS.dds_centro
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsCentro(String ddsCentro) {
        this.ddsCentro = ddsCentro == null ? null : ddsCentro.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_motbaj
     *
     * @return the value of VWDDS.dds_motbaj
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsMotbaj() {
        return ddsMotbaj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_motbaj
     *
     * @param ddsMotbaj the value for VWDDS.dds_motbaj
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsMotbaj(String ddsMotbaj) {
        this.ddsMotbaj = ddsMotbaj == null ? null : ddsMotbaj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_docide
     *
     * @return the value of VWDDS.dds_docide
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsDocide() {
        return ddsDocide;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_docide
     *
     * @param ddsDocide the value for VWDDS.dds_docide
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsDocide(String ddsDocide) {
        this.ddsDocide = ddsDocide == null ? null : ddsDocide.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_nrodoc
     *
     * @return the value of VWDDS.dds_nrodoc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsNrodoc() {
        return ddsNrodoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_nrodoc
     *
     * @param ddsNrodoc the value for VWDDS.dds_nrodoc
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsNrodoc(String ddsNrodoc) {
        this.ddsNrodoc = ddsNrodoc == null ? null : ddsNrodoc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_sexo
     *
     * @return the value of VWDDS.dds_sexo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsSexo() {
        return ddsSexo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_sexo
     *
     * @param ddsSexo the value for VWDDS.dds_sexo
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsSexo(String ddsSexo) {
        this.ddsSexo = ddsSexo == null ? null : ddsSexo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_nacion
     *
     * @return the value of VWDDS.dds_nacion
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsNacion() {
        return ddsNacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_nacion
     *
     * @param ddsNacion the value for VWDDS.dds_nacion
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsNacion(String ddsNacion) {
        this.ddsNacion = ddsNacion == null ? null : ddsNacion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_fecnac
     *
     * @return the value of VWDDS.dds_fecnac
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getDdsFecnac() {
        return ddsFecnac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_fecnac
     *
     * @param ddsFecnac the value for VWDDS.dds_fecnac
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsFecnac(Date ddsFecnac) {
        this.ddsFecnac = ddsFecnac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_userna
     *
     * @return the value of VWDDS.dds_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDdsUserna() {
        return ddsUserna;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_userna
     *
     * @param ddsUserna the value for VWDDS.dds_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsUserna(String ddsUserna) {
        this.ddsUserna = ddsUserna == null ? null : ddsUserna.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWDDS.dds_fecact
     *
     * @return the value of VWDDS.dds_fecact
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getDdsFecact() {
        return ddsFecact;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWDDS.dds_fecact
     *
     * @param ddsFecact the value for VWDDS.dds_fecact
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDdsFecact(Date ddsFecact) {
        this.ddsFecact = ddsFecact;
    }
}