package pe.gob.sunat.recurso2.administracion.siga.registro.model.bean;

import java.util.Date;

public class T733Pernat {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.tip_docide_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String tipDocidePnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.num_docide_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String numDocidePnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.des_apepat_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String desApepatPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.des_apemat_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String desApematPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.des_nombre_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String desNombrePnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.fec_nac_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date fecNacPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.tip_estciv_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String tipEstcivPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.tip_sexo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String tipSexoPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.des_domici_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String desDomiciPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.fec_fall_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date fecFallPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cod_ubigeo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String codUbigeoPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.num_telefo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String numTelefoPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.ind_proced_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String indProcedPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.fec_act_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date fecActPnat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cla_nombre_1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String claNombre1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cla_nombre_2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String claNombre2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cla_nombre_3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String claNombre3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cla_nombre_4
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String claNombre4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cla_direc_1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String claDirec1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cla_direc_2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String claDirec2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cla_direc_3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String claDirec3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.num_paq_actualiza
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String numPaqActualiza;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.ind_novedad
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String indNovedad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.cod_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private String codUserna;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VWT733PERNAT.fec_act
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    private Date fecAct;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.tip_docide_pnat
     *
     * @return the value of VWT733PERNAT.tip_docide_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getTipDocidePnat() {
        return tipDocidePnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.tip_docide_pnat
     *
     * @param tipDocidePnat the value for VWT733PERNAT.tip_docide_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setTipDocidePnat(String tipDocidePnat) {
        this.tipDocidePnat = tipDocidePnat == null ? null : tipDocidePnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.num_docide_pnat
     *
     * @return the value of VWT733PERNAT.num_docide_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getNumDocidePnat() {
        return numDocidePnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.num_docide_pnat
     *
     * @param numDocidePnat the value for VWT733PERNAT.num_docide_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setNumDocidePnat(String numDocidePnat) {
        this.numDocidePnat = numDocidePnat == null ? null : numDocidePnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.des_apepat_pnat
     *
     * @return the value of VWT733PERNAT.des_apepat_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDesApepatPnat() {
        return desApepatPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.des_apepat_pnat
     *
     * @param desApepatPnat the value for VWT733PERNAT.des_apepat_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDesApepatPnat(String desApepatPnat) {
        this.desApepatPnat = desApepatPnat == null ? null : desApepatPnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.des_apemat_pnat
     *
     * @return the value of VWT733PERNAT.des_apemat_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDesApematPnat() {
        return desApematPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.des_apemat_pnat
     *
     * @param desApematPnat the value for VWT733PERNAT.des_apemat_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDesApematPnat(String desApematPnat) {
        this.desApematPnat = desApematPnat == null ? null : desApematPnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.des_nombre_pnat
     *
     * @return the value of VWT733PERNAT.des_nombre_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDesNombrePnat() {
        return desNombrePnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.des_nombre_pnat
     *
     * @param desNombrePnat the value for VWT733PERNAT.des_nombre_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDesNombrePnat(String desNombrePnat) {
        this.desNombrePnat = desNombrePnat == null ? null : desNombrePnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.fec_nac_pnat
     *
     * @return the value of VWT733PERNAT.fec_nac_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getFecNacPnat() {
        return fecNacPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.fec_nac_pnat
     *
     * @param fecNacPnat the value for VWT733PERNAT.fec_nac_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setFecNacPnat(Date fecNacPnat) {
        this.fecNacPnat = fecNacPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.tip_estciv_pnat
     *
     * @return the value of VWT733PERNAT.tip_estciv_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getTipEstcivPnat() {
        return tipEstcivPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.tip_estciv_pnat
     *
     * @param tipEstcivPnat the value for VWT733PERNAT.tip_estciv_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setTipEstcivPnat(String tipEstcivPnat) {
        this.tipEstcivPnat = tipEstcivPnat == null ? null : tipEstcivPnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.tip_sexo_pnat
     *
     * @return the value of VWT733PERNAT.tip_sexo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getTipSexoPnat() {
        return tipSexoPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.tip_sexo_pnat
     *
     * @param tipSexoPnat the value for VWT733PERNAT.tip_sexo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setTipSexoPnat(String tipSexoPnat) {
        this.tipSexoPnat = tipSexoPnat == null ? null : tipSexoPnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.des_domici_pnat
     *
     * @return the value of VWT733PERNAT.des_domici_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getDesDomiciPnat() {
        return desDomiciPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.des_domici_pnat
     *
     * @param desDomiciPnat the value for VWT733PERNAT.des_domici_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setDesDomiciPnat(String desDomiciPnat) {
        this.desDomiciPnat = desDomiciPnat == null ? null : desDomiciPnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.fec_fall_pnat
     *
     * @return the value of VWT733PERNAT.fec_fall_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getFecFallPnat() {
        return fecFallPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.fec_fall_pnat
     *
     * @param fecFallPnat the value for VWT733PERNAT.fec_fall_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setFecFallPnat(Date fecFallPnat) {
        this.fecFallPnat = fecFallPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cod_ubigeo_pnat
     *
     * @return the value of VWT733PERNAT.cod_ubigeo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getCodUbigeoPnat() {
        return codUbigeoPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cod_ubigeo_pnat
     *
     * @param codUbigeoPnat the value for VWT733PERNAT.cod_ubigeo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setCodUbigeoPnat(String codUbigeoPnat) {
        this.codUbigeoPnat = codUbigeoPnat == null ? null : codUbigeoPnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.num_telefo_pnat
     *
     * @return the value of VWT733PERNAT.num_telefo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getNumTelefoPnat() {
        return numTelefoPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.num_telefo_pnat
     *
     * @param numTelefoPnat the value for VWT733PERNAT.num_telefo_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setNumTelefoPnat(String numTelefoPnat) {
        this.numTelefoPnat = numTelefoPnat == null ? null : numTelefoPnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.ind_proced_pnat
     *
     * @return the value of VWT733PERNAT.ind_proced_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getIndProcedPnat() {
        return indProcedPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.ind_proced_pnat
     *
     * @param indProcedPnat the value for VWT733PERNAT.ind_proced_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setIndProcedPnat(String indProcedPnat) {
        this.indProcedPnat = indProcedPnat == null ? null : indProcedPnat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.fec_act_pnat
     *
     * @return the value of VWT733PERNAT.fec_act_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getFecActPnat() {
        return fecActPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.fec_act_pnat
     *
     * @param fecActPnat the value for VWT733PERNAT.fec_act_pnat
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setFecActPnat(Date fecActPnat) {
        this.fecActPnat = fecActPnat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cla_nombre_1
     *
     * @return the value of VWT733PERNAT.cla_nombre_1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getClaNombre1() {
        return claNombre1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cla_nombre_1
     *
     * @param claNombre1 the value for VWT733PERNAT.cla_nombre_1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setClaNombre1(String claNombre1) {
        this.claNombre1 = claNombre1 == null ? null : claNombre1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cla_nombre_2
     *
     * @return the value of VWT733PERNAT.cla_nombre_2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getClaNombre2() {
        return claNombre2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cla_nombre_2
     *
     * @param claNombre2 the value for VWT733PERNAT.cla_nombre_2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setClaNombre2(String claNombre2) {
        this.claNombre2 = claNombre2 == null ? null : claNombre2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cla_nombre_3
     *
     * @return the value of VWT733PERNAT.cla_nombre_3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getClaNombre3() {
        return claNombre3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cla_nombre_3
     *
     * @param claNombre3 the value for VWT733PERNAT.cla_nombre_3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setClaNombre3(String claNombre3) {
        this.claNombre3 = claNombre3 == null ? null : claNombre3.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cla_nombre_4
     *
     * @return the value of VWT733PERNAT.cla_nombre_4
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getClaNombre4() {
        return claNombre4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cla_nombre_4
     *
     * @param claNombre4 the value for VWT733PERNAT.cla_nombre_4
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setClaNombre4(String claNombre4) {
        this.claNombre4 = claNombre4 == null ? null : claNombre4.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cla_direc_1
     *
     * @return the value of VWT733PERNAT.cla_direc_1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getClaDirec1() {
        return claDirec1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cla_direc_1
     *
     * @param claDirec1 the value for VWT733PERNAT.cla_direc_1
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setClaDirec1(String claDirec1) {
        this.claDirec1 = claDirec1 == null ? null : claDirec1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cla_direc_2
     *
     * @return the value of VWT733PERNAT.cla_direc_2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getClaDirec2() {
        return claDirec2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cla_direc_2
     *
     * @param claDirec2 the value for VWT733PERNAT.cla_direc_2
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setClaDirec2(String claDirec2) {
        this.claDirec2 = claDirec2 == null ? null : claDirec2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cla_direc_3
     *
     * @return the value of VWT733PERNAT.cla_direc_3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getClaDirec3() {
        return claDirec3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cla_direc_3
     *
     * @param claDirec3 the value for VWT733PERNAT.cla_direc_3
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setClaDirec3(String claDirec3) {
        this.claDirec3 = claDirec3 == null ? null : claDirec3.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.num_paq_actualiza
     *
     * @return the value of VWT733PERNAT.num_paq_actualiza
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getNumPaqActualiza() {
        return numPaqActualiza;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.num_paq_actualiza
     *
     * @param numPaqActualiza the value for VWT733PERNAT.num_paq_actualiza
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setNumPaqActualiza(String numPaqActualiza) {
        this.numPaqActualiza = numPaqActualiza == null ? null : numPaqActualiza.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.ind_novedad
     *
     * @return the value of VWT733PERNAT.ind_novedad
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getIndNovedad() {
        return indNovedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.ind_novedad
     *
     * @param indNovedad the value for VWT733PERNAT.ind_novedad
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setIndNovedad(String indNovedad) {
        this.indNovedad = indNovedad == null ? null : indNovedad.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.cod_userna
     *
     * @return the value of VWT733PERNAT.cod_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public String getCodUserna() {
        return codUserna;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.cod_userna
     *
     * @param codUserna the value for VWT733PERNAT.cod_userna
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setCodUserna(String codUserna) {
        this.codUserna = codUserna == null ? null : codUserna.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VWT733PERNAT.fec_act
     *
     * @return the value of VWT733PERNAT.fec_act
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public Date getFecAct() {
        return fecAct;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VWT733PERNAT.fec_act
     *
     * @param fecAct the value for VWT733PERNAT.fec_act
     *
     * @ibatorgenerated Wed Feb 08 15:42:39 COT 2017
     */
    public void setFecAct(Date fecAct) {
        this.fecAct = fecAct;
    }
}