package pe.gob.sunat.recurso2.administracion.siga.firma.model.dao;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import pe.gob.sunat.recurso2.administracion.siga.firma.model.bean.T7074DocumentoFirm;

public interface T7074DocumentoFirmDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7074DOCUMENTOFIRM
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    int deleteByPrimaryKey(BigDecimal codDocaut);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7074DOCUMENTOFIRM
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    void insert(T7074DocumentoFirm record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7074DOCUMENTOFIRM
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    void insertSelective(T7074DocumentoFirm record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7074DOCUMENTOFIRM
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    T7074DocumentoFirm selectByPrimaryKey(BigDecimal codDocaut);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7074DOCUMENTOFIRM
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    int updateByPrimaryKeySelective(T7074DocumentoFirm record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T7074DOCUMENTOFIRM
     *
     * @ibatorgenerated Wed Mar 30 14:05:42 COT 2016
     */
    int updateByPrimaryKey(T7074DocumentoFirm record);
    
    public List<T7074DocumentoFirm> listByParameter(T7074DocumentoFirm param);
    
    public List<T7074DocumentoFirm> listByParameterConDatosFirmantes(T7074DocumentoFirm param);
    
    int updateEstadoDocumento(T7074DocumentoFirm record);
    
    public Long obtenerSecuencial() throws Exception;
    public Long obtenerSecuencialFirmaSiga() throws Exception; //Para el cambio de Firma
    
  	public String encriptaCadena(Map parm);

  	public String desencriptaCadena(Map parm);
}